export const SEND_FORM_DATA  ="SEND_FORM_DATA "
export const SEND_FAILURE_SAGA ="SEND_FAILURE_SAGA"
export const SEND_SUCCESS_SAGA ="SEND_SUCCESS_SAGA"
export const  GET_FROM_DATA =" GET_FROM_DATA"

export const GET_SUCCESS_SAGA ="GET_SUCCESS_SAGA"
export const GET_FAILURE_SAGA ="GET_FAILURE_SAGA"
export const REMOVE_FROM_DATA ="REMOVE_FROM_DATA"
export const DELETE_ITEM_SUCCESS_SAGA ="DELETE_ITEM_SUCCESS_SAGA"
export const DELETE_ITEM_FAILURE_SAGA ="DELETE_ITEM_FAILURE_SAGA"
export const DELETE_ITEM_SUCCESS ="DELETE_ITEM_SUCCESS"






